import React, { useState, useEffect } from 'react';
import { X, Search, Mail, Film, Image as ImageIcon, Edit, Minimize2, DollarSign, ShoppingBag, Link, Save, Loader, Trash } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { INQUIRY_CATEGORIES } from '../../config/constants';
import { formatDateLocal } from '../../utils/dateUtils';

export const TeamMemberDetailModal = () => { const { modals, toggleModal } = useApp(); if (!modals.memberDetail) return null; return <div className="fixed inset-0 z-50 bg-[#42392e]/50" onClick={() => toggleModal('memberDetail', false)} />; };

export const DetailModal = () => {
    const { modals, toggleModal, selectedItems, setSelectedItems, setModalType } = useApp(); if (!modals.detail || !selectedItems.management) return null; const item = selectedItems.management; return (<div className="fixed inset-0 z-[120] flex items-center justify-center bg-[#42392e]/30 p-4"><div className="bg-[#faf6ef] p-6 rounded-lg max-w-sm w-full"><h3 className="font-bold mb-4">{item.title || item.product || item.sender || '상세'}</h3><div className="text-sm mb-4 text-[#5a4d40] space-y-2">
        {item.type && <p><span className="font-bold">구분:</span> {item.type === 'income' ? '수입' : item.type === 'expense' ? '지출' : item.type}</p>}
        {item.amount && <p><span className="font-bold">금액:</span> ₩{Number(item.amount).toLocaleString()}</p>}
        {item.datetime && <p><span className="font-bold">날짜:</span> {item.datetime}</p>}
        {item.receivedDate && <p><span className="font-bold">수신일:</span> {item.receivedDate}</p>}
        {item.sender && <p><span className="font-bold">발신자:</span> {item.sender}</p>}
        {item.subject && <p><span className="font-bold">제목:</span> {item.subject}</p>}
        {item.content && <p><span className="font-bold">내용:</span> {item.content}</p>}
        {item.memo && <p><span className="font-bold">메모:</span> {item.memo}</p>}
    </div><div className="flex justify-end gap-2"><button onClick={() => { setSelectedItems(prev => ({ ...prev, edit: item })); setModalType(item.type); toggleModal('detail', false); if (item.category === 'finance') toggleModal('finance', true); else toggleModal('external', true); }} className="px-3 py-1 bg-[#5d6a7a]/20 text-[#4d5a6a] rounded">수정</button><button onClick={() => toggleModal('detail', false)} className="px-3 py-1 bg-[#f5f0e6] rounded">닫기</button></div></div></div>);
};

export const ReportDraftModal = () => { const { modals, toggleModal } = useApp(); if (!modals.report) return null; return (<div className="fixed inset-0 z-[100] bg-[#42392e]/30 flex items-center justify-center"><div className="bg-[#faf6ef] p-6 rounded-xl"><div className="text-center p-4">리포트 초안 기능 준비중</div><button onClick={() => toggleModal('report', false)} className="bg-[#f5f0e6] px-4 py-2 rounded">닫기</button></div></div>); };

export const ExternalModal = () => {
    const { modals, toggleModal, operations, modalType, selectedItems, showToast } = useApp(); const [d, setD] = useState({}); useEffect(() => { if (modals.external && selectedItems.edit) setD(selectedItems.edit); else setD({}); }, [modals.external, selectedItems.edit]); if (!modals.external) return null; const handleSubmit = async () => {
        const category = d.category || 'inquiry';
        if (await operations.saveManagement({ ...d, type: modalType, category }, category)) { showToast('저장됨'); toggleModal('external', false); } else { showToast('실패', 'error'); }
    }; return (<div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#42392e]/30"><div className="bg-[#faf6ef] p-6 rounded-xl w-80"><h3 className="font-bold mb-2 uppercase">{modalType}</h3><input placeholder={modalType === 'sponsor' ? "제품명" : "발신자"} value={d.sender || d.product || ''} className="border w-full p-2 mb-4 rounded text-[#32291e]" onChange={e => setD({ ...d, [modalType === 'sponsor' ? 'product' : 'sender']: e.target.value })} /><button onClick={handleSubmit} className="bg-[#4d5a6a] text-[#faf6ef] w-full p-2 rounded mb-2">저장</button><button onClick={() => toggleModal('external', false)} className="w-full text-[#857460]">취소</button></div></div>);
};

export const SearchResultModal = () => { const { modals, toggleModal, searchTerm, plans, setSelectedItems } = useApp(); if (!modals.search) return null; const filteredPlans = plans.filter(p => p.topic?.includes(searchTerm) || p.description?.includes(searchTerm) || p.planner?.includes(searchTerm)); return (<div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#3a2d20]/80 backdrop-blur-md p-4 animate-in fade-in duration-200"><div className="bg-[#faf6ef] w-full max-w-4xl rounded-2xl shadow-2xl flex flex-col max-h-[85vh]"><div className="p-5 border-b border-[#e8dcc8] flex justify-between items-center bg-[#4d5a6a] rounded-t-2xl text-[#faf6ef]"><h3 className="font-bold text-lg flex items-center gap-2"><Search size={20} /> 검색 결과: "{searchTerm}"</h3><button onClick={() => toggleModal('search', false)} className="hover:bg-[#faf6ef]/20 p-1 rounded-full transition-colors"><X size={20} /></button></div><div className="p-6 overflow-y-auto bg-[#faf6ef] flex-1 flex flex-col gap-6"><div className="bg-[#faf6ef] p-5 rounded-xl border border-[#d4c4ac] shadow-sm"><h4 className="font-bold text-[#42392e] mb-3 flex items-center gap-2"><Film size={18} className="text-[#5d6a7a]" /> 프로젝트 ({filteredPlans.length})</h4>{filteredPlans.length > 0 ? (<div className="space-y-2">{filteredPlans.map(p => (<div key={p.id} onClick={() => { toggleModal('search', false); setSelectedItems(prev => ({ ...prev, plan: p })); toggleModal('plan', true); }} className="p-3 border border-[#e8dcc8] rounded-lg hover:bg-[#5d6a7a]/10 transition-colors cursor-pointer"><div className="font-bold text-[#4a3d30]">{p.topic}</div><div className="text-xs text-[#6a5d50] mt-1">담당: {p.planner} | 마감: {p.uploadDate}</div></div>))}</div>) : <div className="text-[#857460] text-sm">결과 없음</div>}</div></div><div className="p-5 border-t border-[#e8dcc8] flex justify-end gap-3 rounded-b-2xl bg-[#faf6ef]"><button onClick={() => toggleModal('search', false)} className="px-6 py-2.5 bg-[#4a3d30] text-[#faf6ef] font-bold rounded-xl hover:bg-[#5a4d40]">닫기</button></div></div></div>); };

export const ThumbnailModal = () => { const { modals, toggleModal } = useApp(); const [scenario, setScenario] = useState(''); const [isGenerating, setIsGenerating] = useState(false); const [generatedImage, setGeneratedImage] = useState(null); if (!modals.thumbnail) return null; const handleGenerate = async () => { if (!scenario.trim()) return; setIsGenerating(true); setTimeout(() => { setGeneratedImage("https://via.placeholder.com/600x400.png?text=AI+Thumbnail+Preview"); setIsGenerating(false); }, 2000); }; return (<div className="fixed inset-0 z-[120] flex items-center justify-center bg-[#42392e]/50 backdrop-blur-sm p-4 animate-in fade-in zoom-in-95 duration-200"><div className="bg-[#faf6ef] w-full max-w-4xl rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]"><div className="p-5 border-b border-[#e8dcc8] flex justify-between items-center bg-gradient-to-r from-[#faf6ef] to-[#f5f0e6]"><h3 className="font-black text-xl text-[#42392e] flex items-center gap-2"><Edit className="text-violet-600" size={24} /> AI 섬네일 스튜디오 <span className="text-xs bg-[#faf6ef]/50 px-2 py-1 rounded text-[#6a5d7a] border border-violet-100">PRO</span></h3><button onClick={() => toggleModal('thumbnail', false)}><X size={24} className="text-[#857460] hover:text-[#5a4d40]" /></button></div><div className="p-6 flex flex-col lg:flex-row gap-8 overflow-y-auto"><div className="flex-1 flex flex-col gap-6 min-w-[300px]"><div><label className="block text-xs font-bold text-[#6a5d50] mb-2 uppercase">영상 시나리오 입력</label><textarea className="w-full p-4 bg-[#faf6ef] border border-[#d4c4ac] rounded-xl h-32 text-[#32291e]" placeholder="예: 봄 신상 후드티 룩북 촬영..." value={scenario} onChange={(e) => setScenario(e.target.value)} /></div><button onClick={handleGenerate} disabled={isGenerating || !scenario} className="w-full py-4 vj-btn-primary text-[#faf6ef] font-bold rounded-xl shadow-lg">{isGenerating ? '생성 중...' : '섬네일 생성 시작'}</button></div><div className="flex-[1.5] bg-[#3a2d20] rounded-2xl flex items-center justify-center min-h-[400px]">{generatedImage ? <img src={generatedImage} alt="Gen" className="w-full h-full object-contain" /> : <ImageIcon size={32} className="opacity-50 text-[#faf6ef]" />}</div></div></div></div>); };
