// DashboardTab, ScheduleTab, CalendarTab 
// 원본 파일 라인 2065~2539 에서 추출
// 이 파일은 원본의 해당 섹션을 그대로 모듈화한 것입니다.

import React, { useState, useMemo } from 'react';
import { Plus, Film, DollarSign, Layout, User, CheckCircle, ClipboardList, Activity, Calendar as CalendarIcon, ChevronLeft, ChevronRight, LayoutGrid, Columns, X, Edit, Filter } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { TEAM_MEMBERS, HOLIDAYS } from '../../config/constants';
import { formatDateLocal, getWeekDays, parseLocalDate } from '../../utils/dateUtils';
import { MonthView, WeekView } from '../views/CalendarViews';

export const DashboardTab = () => {
    const { profile, plans, filteredTasks, managements, logs, toggleModal, setSelectedItems, setSelectedDate } = useApp();
    const today = formatDateLocal(new Date());
    const [selectedStatus, setSelectedStatus] = useState(null);
    const weekDays = useMemo(() => getWeekDays(new Date()), []);
    const myTasks = useMemo(() => filteredTasks.filter(t => !t.isDraftPlaceholder && t.author === profile), [filteredTasks, profile]);
    const myTasksByDate = useMemo(() => { const map = {}; weekDays.forEach(day => { const dateStr = formatDateLocal(day); map[dateStr] = myTasks.filter(t => t.workStartDate <= dateStr && t.workEndDate >= dateStr); }); return map; }, [myTasks, weekDays]);
    const weekTasks = useMemo(() => { const weekStartStr = formatDateLocal(weekDays[0]); const weekEndStr = formatDateLocal(weekDays[6]); return filteredTasks.filter(t => { if (t.isDraftPlaceholder) return false; return t.workStartDate <= weekEndStr && t.workEndDate >= weekStartStr; }); }, [filteredTasks, weekDays]);
    const weekSummary = useMemo(() => ({ total: weekTasks.length, done: weekTasks.filter(t => t.status === 'done').length, inProgress: weekTasks.filter(t => t.status === 'in_progress').length, todo: weekTasks.filter(t => t.status === 'todo').length }), [weekTasks]);
    const selectedTasks = useMemo(() => { if (!selectedStatus) return []; if (selectedStatus === 'all') return weekTasks; return weekTasks.filter(t => t.status === selectedStatus); }, [selectedStatus, weekTasks]);
    const todayTasks = useMemo(() => filteredTasks.filter(t => !t.isDraftPlaceholder && t.workStartDate <= today && t.workEndDate >= today && t.status !== 'done').slice(0, 5), [filteredTasks, today]);
    const activeProjects = useMemo(() => plans.filter(p => p.status === 'active').map(plan => { const planTasks = filteredTasks.filter(t => t.planId === plan.id && !t.isDraftPlaceholder); let totalDays = 0, completedDays = 0; planTasks.forEach(t => { const start = parseLocalDate(t.workStartDate); const end = parseLocalDate(t.workEndDate); const duration = Math.floor((end - start) / (1000 * 60 * 60 * 24)) + 1; if (duration > 0) totalDays += duration; if (t.completedDates) completedDays += t.completedDates.length; }); return { ...plan, progress: totalDays === 0 ? 0 : Math.min(100, Math.round((completedDays / totalDays) * 100)) }; }).sort((a, b) => b.progress - a.progress).slice(0, 3), [plans, filteredTasks]);
    const teamStatus = useMemo(() => TEAM_MEMBERS.map(member => { const memberTasks = filteredTasks.filter(t => t.author === member && !t.isDraftPlaceholder && t.workStartDate <= today && t.workEndDate >= today); const doing = memberTasks.find(t => t.status === 'in_progress'); return { name: member, taskCount: memberTasks.length, currentTask: doing?.details || (memberTasks[0]?.details || '예정된 업무 없음') }; }), [filteredTasks, today]);
    const recentLogs = useMemo(() => logs.slice(0, 5), [logs]);
    const financeSummary = useMemo(() => { const thisMonth = new Date(); const monthItems = managements.filter(m => m.category === 'finance' && m.datetime && (() => { const d = new Date(m.datetime); return d.getMonth() === thisMonth.getMonth() && d.getFullYear() === thisMonth.getFullYear(); })()); const income = monthItems.filter(i => i.type === 'income').reduce((sum, i) => sum + (Number(i.amount) || 0), 0); const expense = monthItems.filter(i => i.type === 'expense').reduce((sum, i) => sum + (Number(i.amount) || 0), 0); return { income, expense, balance: income - expense }; }, [managements]);

    const statusCards = [
        { key: 'all', label: '이번 주 전체', count: weekSummary.total, unit: '개의 업무', activeColor: 'border-[#a0714a] ring-2 ring-[#a0714a]/30', countColor: 'text-[#42392e]', badgeColor: 'bg-[#a0714a] text-[#faf6ef]' },
        { key: 'done', label: '완료', count: weekSummary.done, unit: '개 완료', activeColor: 'border-[#5d7a5d] ring-2 ring-[#5d7a5d]/30', countColor: 'text-[#5d7a5d]', badgeColor: 'bg-[#5d7a5d] text-[#faf6ef]' },
        { key: 'in_progress', label: '진행중', count: weekSummary.inProgress, unit: '개 진행중', activeColor: 'border-[#a0714a] ring-2 ring-[#a0714a]/30', countColor: 'text-[#a0714a]', badgeColor: 'bg-[#a0714a] text-[#faf6ef]' },
        { key: 'todo', label: '대기', count: weekSummary.todo, unit: '개 대기', activeColor: 'border-[#857460] ring-2 ring-[#857460]/30', countColor: 'text-[#857460]', badgeColor: 'bg-[#857460] text-[#faf6ef]' },
    ];
    const statusLabel = { all: '이번 주 전체', done: '완료', in_progress: '진행중', todo: '대기' };
    const getBarStyle = (task) => { if (task.type === 'personal') { const cat = task.category?.[0]; const personalEmoji = { '연차': '🏖️', '오전반차': '🌅', '오후반차': '🌇', '외근': '🗺️', '미팅': '🤝', '기타': '🙂' }; return { bg: 'bg-amber-900/30 border-[#a0714a]/40', text: 'text-[#6a4a2a]', emoji: personalEmoji[cat] || '👤' }; } const cat = task.category?.[0]; const styles = { '대본': { bg: 'bg-blue-900/30 border-[#5d6a7a]/40', text: 'text-[#2d3d4a]', emoji: '📝' }, '촬영': { bg: 'bg-orange-900/30 border-orange-500/40', text: 'text-[#5a3000]', emoji: '🎥' }, '편집': { bg: 'bg-emerald-900/30 border-[#5d7a5d]/40', text: 'text-[#1d4a1d]', emoji: '✂️' }, '업데이트': { bg: 'bg-purple-900/30 border-purple-500/40', text: 'text-[#3a1d5a]', emoji: '🔄' }, }; return styles[cat] || { bg: 'bg-[#857460]/20 border-[#857460]/40', text: 'text-[#4a3d30]', emoji: '📋' }; };
    const DAY_NAMES_KR = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'];

    return (
        <div className="space-y-6">
            <div className="vj-card bg-[#faf6ef] rounded-2xl p-6 border border-[#d4c4ac]">
                <div className="flex items-center justify-between mb-5"><div><h2 className="text-2xl font-black text-[#42392e]">안녕하세요, {profile}님 👋</h2><p className="text-sm text-[#857460] mt-1">{new Date().toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' })} · 이번 주 업무 현황입니다</p></div><button onClick={() => { setSelectedDate(today); setSelectedItems(prev => ({ ...prev, task: { type: 'personal', author: profile, category: ['기타'], workStartDate: today, workEndDate: today, status: 'todo', completedDates: [] } })); toggleModal('schedule', true); }} className="px-4 py-2.5 bg-[#f0e9de] border border-[#d4c4ac] text-[#42392e] font-bold rounded-xl text-sm flex items-center gap-2 hover:bg-[#e8dcc8] transition-all"><Plus size={16} /> 🙂 개인 일정 추가</button></div>
                <div className="flex items-center gap-2 mb-3"><span className="text-xs font-bold text-[#a0714a]">📅 이번 주 내 일정 타임라인</span><span className="text-[10px] text-[#a89880]">빈 칸 클릭 → 빠른 등록 · 항목 클릭 → 수정</span><div className="ml-auto flex items-center gap-3">{[['📝', '대본'], ['🎥', '촬영'], ['✂️', '편집'], ['🔄', '업데이트'], ['👤', '개인']].map(([emoji, label]) => (<span key={label} className="text-[10px] text-[#a89880] flex items-center gap-1">{emoji} {label}</span>))}</div></div>
                <div className="grid grid-cols-7 gap-2">{weekDays.map((day, i) => { const dateStr = formatDateLocal(day); const isToday = dateStr === today; const dayTasks = myTasksByDate[dateStr] || []; const isWeekend = i === 0 || i === 6; const holidayName = HOLIDAYS[dateStr]; return (<div key={dateStr} className={`rounded-xl border overflow-hidden flex flex-col transition-all ${isToday ? 'border-[#a0714a] border-2 shadow-md' : 'border-[#e8dcc8] hover:border-[#a0714a]/50'} bg-[#f5f0e6]`}><div onClick={() => { setSelectedDate(dateStr); setSelectedItems(prev => ({ ...prev, task: null })); toggleModal('schedule', true); }} className={`px-2 py-2 border-b border-[#e8dcc8] flex flex-col items-center cursor-pointer hover:bg-[#e8dcc8] transition-all ${isToday ? 'bg-[#a0714a]/10' : 'bg-[#f0e9de]'}`}><span className={`text-[10px] font-bold ${isWeekend ? 'text-[#9b4d4d]' : isToday ? 'text-[#a0714a]' : 'text-[#a89880]'}`}>{isToday ? `${DAY_NAMES_KR[i]} ✦` : DAY_NAMES_KR[i]}</span><span className={`text-lg font-black leading-tight ${isToday ? 'text-[#a0714a]' : (isWeekend ? 'text-[#9b4d4d]' : 'text-[#42392e]')}`}>{day.getDate()}</span>{holidayName && <span className="text-[8px] text-[#9b4d4d] truncate w-full text-center">{holidayName}</span>}</div><div className="flex-1 p-1.5 flex flex-col gap-1 min-h-[80px]">{dayTasks.slice(0, 3).map(task => { const style = getBarStyle(task); const isDone = task.status === 'done'; return (<div key={task.id} onClick={() => { setSelectedItems(prev => ({ ...prev, task })); toggleModal('schedule', true); }} className={`px-1.5 py-1 rounded text-[10px] font-bold border truncate flex items-center gap-1 cursor-pointer hover:brightness-90 transition-all ${style.bg} ${style.text} ${isDone ? 'opacity-50 line-through decoration-current' : ''}`} title={task.details}><span>{style.emoji}</span><span className="truncate">{task.details || task.category?.[0] || '업무'}</span></div>); })}{dayTasks.length > 3 && (<div className="text-[9px] text-[#a89880] text-center font-bold">+{dayTasks.length - 3}개 더</div>)}<div onClick={() => { setSelectedDate(dateStr); setSelectedItems(prev => ({ ...prev, task: null })); toggleModal('schedule', true); }} className="mt-auto px-1.5 py-1 rounded text-[10px] text-[#c4b49a] border border-dashed border-[#d4c4ac] text-center cursor-pointer hover:border-[#a0714a] hover:text-[#a0714a] hover:bg-[#faf6ef] transition-all">＋</div></div></div>); })}</div>
            </div>
            <div className="grid grid-cols-4 gap-4">{statusCards.map(card => { const isActive = selectedStatus === card.key; return (<button key={card.key} onClick={() => setSelectedStatus(isActive ? null : card.key)} className={`vj-card bg-[#faf6ef] rounded-2xl p-5 border text-left transition-all hover:shadow-md hover:-translate-y-0.5 ${isActive ? card.activeColor : 'border-[#d4c4ac]'}`}><div className="flex justify-between items-start mb-2"><div className={`text-xs font-bold ${isActive ? card.countColor : 'text-[#857460]'}`}>{card.label}</div>{isActive && <span className={`text-[10px] px-2 py-0.5 rounded-full font-bold ${card.badgeColor}`}>선택됨</span>}</div><div className={`text-3xl font-black ${card.countColor}`}>{card.count}</div><div className="text-xs text-[#a89880] mt-1">{card.unit}</div><div className={`text-[10px] mt-3 font-bold transition-all ${isActive ? card.countColor : 'text-[#d4c4ac]'}`}>{isActive ? '▲ 목록 닫기' : '▼ 목록 보기'}</div></button>); })}</div>
            {selectedStatus && (<div className="vj-card bg-[#faf6ef] rounded-2xl border border-[#a0714a] overflow-hidden animate-in slide-in-from-top-2 duration-200"><div className="px-5 py-3 bg-[#f0e9de] border-b border-[#d4c4ac] flex items-center justify-between"><h3 className="font-bold text-[#42392e] flex items-center gap-2"><ClipboardList size={16} className="text-[#a0714a]" />{statusLabel[selectedStatus]} 업무 목록<span className="text-xs bg-[#a0714a]/20 text-[#a0714a] px-2 py-0.5 rounded-full font-bold">{selectedTasks.length}건</span></h3><button onClick={() => setSelectedStatus(null)} className="p-1 rounded-full hover:bg-[#e8dcc8]"><X size={16} className="text-[#857460]" /></button></div>{selectedTasks.length === 0 ? (<div className="py-12 text-center"><CheckCircle size={36} className="text-[#d4c4ac] mx-auto mb-3" /><p className="text-sm text-[#857460]">해당하는 업무가 없습니다.</p></div>) : (<div className="divide-y divide-[#f0e9de] max-h-[360px] overflow-y-auto custom-scrollbar">{selectedTasks.map(task => { const linkedPlan = plans.find(p => p.id === task.planId); const statusBadge = { done: 'bg-[#5d7a5d]/20 text-[#5d7a5d]', in_progress: 'bg-[#a0714a]/20 text-[#a0714a]', todo: 'bg-[#857460]/20 text-[#857460]' }; const statusIcon = task.status === 'done' ? <CheckCircle size={16} className="text-[#5d7a5d] flex-shrink-0" /> : task.status === 'in_progress' ? <Activity size={16} className="text-[#a0714a] flex-shrink-0" /> : <div className="w-4 h-4 rounded-full border-2 border-[#d4c4ac] flex-shrink-0" />; const style = getBarStyle(task); return (<div key={task.id} onClick={() => { setSelectedItems(prev => ({ ...prev, task })); toggleModal('schedule', true); }} className="flex items-center gap-4 px-5 py-3 hover:bg-[#f5f0e6] cursor-pointer transition-all group">{statusIcon}<span className="text-base flex-shrink-0">{style.emoji}</span><div className="flex-1 min-w-0"><div className={`text-sm font-bold truncate ${task.status === 'done' ? 'line-through text-[#a89880]' : 'text-[#42392e]'}`}>{task.details || '내용 없음'}</div><div className="flex items-center gap-2 mt-0.5">{linkedPlan && <span className="text-[10px] bg-[#f0e9de] border border-[#d4c4ac] px-1.5 py-0.5 rounded text-[#6a5d50] truncate max-w-[150px]">{linkedPlan.topic}</span>}{task.category?.map(c => <span key={c} className="text-[10px] text-[#857460]">#{c}</span>)}</div></div><span className="text-xs text-[#857460] flex items-center gap-1 flex-shrink-0"><User size={12} /> {task.author}</span><span className="text-[10px] text-[#a89880] font-mono flex-shrink-0 hidden md:block">{task.workStartDate} ~ {task.workEndDate}</span><span className={`text-[10px] px-2 py-1 rounded-full font-bold flex-shrink-0 ${statusBadge[task.status]}`}>{task.status === 'done' ? '완료' : task.status === 'in_progress' ? '진행중' : '대기'}</span><Edit size={14} className="text-[#d4c4ac] group-hover:text-[#a0714a] transition-colors flex-shrink-0" /></div>); })}</div>)}</div>)}
            <div className="grid grid-cols-2 gap-6">
                <div className="vj-card bg-[#faf6ef] rounded-2xl p-5 border border-[#d4c4ac]"><h3 className="text-lg font-bold text-[#42392e] flex items-center gap-2 mb-4"><CalendarIcon size={20} className="text-[#a0714a]" /> 오늘 할 일</h3>{todayTasks.length === 0 ? (<div className="text-center py-8 text-[#857460]"><CheckCircle size={32} className="mx-auto mb-2 opacity-50" /><p className="text-sm">오늘 예정된 업무가 없습니다</p></div>) : (<div className="space-y-2">{todayTasks.map(task => { const style = getBarStyle(task); return (<div key={task.id} onClick={() => { setSelectedItems(prev => ({ ...prev, task })); toggleModal('schedule', true); }} className="p-3 bg-[#f0e9de] rounded-xl cursor-pointer hover:bg-[#e8dcc8] transition-all border border-[#d4c4ac]"><div className="flex items-center justify-between"><span className="text-sm font-bold text-[#42392e] truncate flex items-center gap-1.5"><span>{style.emoji}</span>{task.details || '내용 없음'}</span><span className="text-xs text-[#857460]">{task.author}</span></div>{task.category && task.category.length > 0 && (<div className="flex gap-1 mt-1">{task.category.map(c => <span key={c} className="text-[10px] bg-[#a0714a]/20 text-[#a0714a] px-1.5 py-0.5 rounded">{c}</span>)}</div>)}</div>); })}</div>)}</div>
                <div className="vj-card bg-[#faf6ef] rounded-2xl p-5 border border-[#d4c4ac]"><h3 className="text-lg font-bold text-[#42392e] flex items-center gap-2 mb-4"><User size={20} className="text-[#a0714a]" /> 팀원별 현황</h3><div className="space-y-3">{teamStatus.map(member => (<div key={member.name} className="flex items-center gap-3 p-3 bg-[#f0e9de] rounded-xl border border-[#d4c4ac]"><div className="w-10 h-10 bg-gradient-to-br from-[#a0714a] to-[#8a5d3a] rounded-full flex items-center justify-center"><span className="text-sm font-black text-[#faf6ef]">{member.name[0]}</span></div><div className="flex-1 min-w-0"><div className="text-sm font-bold text-[#42392e]">{member.name}</div><div className="text-xs text-[#857460] truncate">{member.currentTask}</div></div><div className="text-xs font-bold text-[#a0714a] bg-[#a0714a]/20 px-2 py-1 rounded-full">{member.taskCount}건</div></div>))}</div></div>
            </div>
            <div className="grid grid-cols-3 gap-6">
                <div className="vj-card bg-[#faf6ef] rounded-2xl p-5 border border-[#d4c4ac]"><h3 className="text-lg font-bold text-[#42392e] flex items-center gap-2 mb-4"><Film size={20} className="text-[#a0714a]" /> 진행중 프로젝트</h3>{activeProjects.length === 0 ? (<div className="text-center py-6 text-[#857460]"><Layout size={32} className="mx-auto mb-2 opacity-50" /><p className="text-sm">진행중인 프로젝트 없음</p></div>) : (<div className="space-y-3">{activeProjects.map(project => (<div key={project.id} onClick={() => { setSelectedItems(prev => ({ ...prev, plan: project })); toggleModal('plan', true); }} className="cursor-pointer hover:bg-[#f0e9de] p-2 rounded-lg transition-all"><div className="flex items-center justify-between mb-1"><span className="text-sm font-bold text-[#42392e] truncate">🎬 {project.topic}</span><span className="text-xs font-bold text-[#a0714a]">{project.progress}%</span></div><div className="h-2 bg-[#e8dcc8] rounded-full overflow-hidden"><div className="h-full bg-[#a0714a] transition-all" style={{ width: `${project.progress}%` }} /></div></div>))}</div>)}</div>
                <div className="vj-card bg-[#faf6ef] rounded-2xl p-5 border border-[#d4c4ac]"><h3 className="text-lg font-bold text-[#42392e] flex items-center gap-2 mb-4"><Activity size={20} className="text-[#a0714a]" /> 최근 활동</h3>{recentLogs.length === 0 ? (<div className="text-center py-6 text-[#857460]"><Activity size={32} className="mx-auto mb-2 opacity-50" /><p className="text-sm">활동 기록 없음</p></div>) : (<div className="space-y-2">{recentLogs.map((log, idx) => (<div key={log.id || idx} className="flex items-start gap-2 text-xs"><div className="w-1.5 h-1.5 rounded-full bg-[#a0714a] mt-1.5 flex-shrink-0" /><div className="flex-1 min-w-0"><span className="text-[#42392e]">{log.message}</span><div className="text-[#a89880] mt-0.5">{log.user} · {new Date(log.createdAt).toLocaleDateString('ko-KR')}</div></div></div>))}</div>)}</div>
                <div className="vj-card bg-[#faf6ef] rounded-2xl p-5 border border-[#d4c4ac]"><h3 className="text-lg font-bold text-[#42392e] flex items-center gap-2 mb-4"><DollarSign size={20} className="text-[#a0714a]" /> 이번 달 재무</h3><div className="space-y-3"><div className="flex justify-between items-center p-3 bg-[#5d7a5d]/10 rounded-xl"><span className="text-sm text-[#5d7a5d] font-bold">💰 수입</span><span className="text-lg font-black text-[#5d7a5d]">₩{financeSummary.income.toLocaleString()}</span></div><div className="flex justify-between items-center p-3 bg-[#9b4d4d]/10 rounded-xl"><span className="text-sm text-[#9b4d4d] font-bold">💸 지출</span><span className="text-lg font-black text-[#9b4d4d]">₩{financeSummary.expense.toLocaleString()}</span></div><div className="flex justify-between items-center p-3 bg-[#a0714a]/10 rounded-xl border-t-2 border-[#a0714a]"><span className="text-sm text-[#42392e] font-bold">📊 잔액</span><span className={`text-lg font-black ${financeSummary.balance >= 0 ? 'text-[#5d7a5d]' : 'text-[#9b4d4d]'}`}>₩{financeSummary.balance.toLocaleString()}</span></div></div></div>
            </div>
        </div>
    );
};

export const ScheduleTab = () => {
    const { viewMode, setViewMode, currentDate, next, prev, today, selectedAuthors, setSelectedAuthors, toggleAuthor } = useApp();
    const monthStr = `${currentDate.getFullYear()}년 ${currentDate.getMonth() + 1}월`;
    const scheduleViewMode = viewMode === 'kanban' ? 'month' : viewMode;
    return (<div className="space-y-4"><div className="vj-card bg-[#faf6ef] rounded-2xl p-4 border border-[#d4c4ac]"><div className="flex items-center justify-between"><div className="flex items-center gap-4"><h2 className="text-2xl font-black text-[#42392e] flex items-center gap-2"><CalendarIcon size={24} className="text-[#a0714a]" />{monthStr}</h2><div className="flex gap-1"><button onClick={prev} className="p-2 bg-[#f5f0e6] hover:bg-[#e8dcc8] rounded-lg transition-all"><ChevronLeft size={18} className="text-[#857460]" /></button><button onClick={today} className="px-3 py-2 bg-[#f5f0e6] hover:bg-[#e8dcc8] rounded-lg text-xs font-bold text-[#42392e] transition-all">Today</button><button onClick={next} className="p-2 bg-[#f5f0e6] hover:bg-[#e8dcc8] rounded-lg transition-all"><ChevronRight size={18} className="text-[#857460]" /></button></div></div><div className="flex items-center gap-4"><div className="flex items-center gap-1 p-1 bg-[#f0e9de] rounded-xl"><span className="text-xs text-[#857460] font-bold px-2">팀원</span><button onClick={() => setSelectedAuthors([])} className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${selectedAuthors.length === 0 ? 'bg-[#a0714a] text-[#faf6ef]' : 'text-[#857460] hover:bg-[#e8dcc8]'}`}>전체</button>{TEAM_MEMBERS.map(m => (<button key={m} onClick={() => toggleAuthor(m)} className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${selectedAuthors.includes(m) ? 'bg-[#a0714a] text-[#faf6ef]' : 'text-[#857460] hover:bg-[#e8dcc8]'}`}>{m}</button>))}</div><div className="flex items-center gap-1 p-1 bg-[#f0e9de] rounded-xl"><span className="text-xs text-[#857460] font-bold px-2">보기</span><button onClick={() => setViewMode('month')} className={`px-4 py-2 rounded-lg text-xs font-bold flex items-center gap-2 transition-all ${scheduleViewMode === 'month' ? 'bg-[#a0714a] text-[#faf6ef]' : 'text-[#857460] hover:bg-[#e8dcc8]'}`}><LayoutGrid size={14} />월간</button><button onClick={() => setViewMode('week')} className={`px-4 py-2 rounded-lg text-xs font-bold flex items-center gap-2 transition-all ${scheduleViewMode === 'week' ? 'bg-[#a0714a] text-[#faf6ef]' : 'text-[#857460] hover:bg-[#e8dcc8]'}`}><Columns size={14} />주간</button></div></div></div></div>
        <div className="vj-card bg-[#faf6ef] rounded-2xl border border-[#d4c4ac] overflow-hidden h-[700px]"><div className="px-6 py-3 border-b border-[#d4c4ac] bg-[#f0e9de] flex items-center gap-4 overflow-x-auto no-scrollbar"><span className="text-xs text-[#a89880] font-bold mr-2 whitespace-nowrap">업무 구분:</span><div className="flex items-center gap-1 whitespace-nowrap"><div className="w-3 h-3 bg-blue-900/40 border border-[#5d6a7a]/40 rounded" /><span className="text-xs text-[#857460]">대본</span></div><div className="flex items-center gap-1 whitespace-nowrap"><div className="w-3 h-3 bg-rose-900/40 border border-[#9b4d4d]/40 rounded" /><span className="text-xs text-[#857460]">촬영</span></div><div className="flex items-center gap-1 whitespace-nowrap"><div className="w-3 h-3 bg-indigo-900/40 border border-[#6a5d7a]/40 rounded" /><span className="text-xs text-[#857460]">편집</span></div><div className="flex items-center gap-1 whitespace-nowrap"><div className="w-3 h-3 bg-emerald-900/40 border border-[#5d7a5d]/40 rounded" /><span className="text-xs text-[#857460]">업데이트</span></div><div className="flex items-center gap-1 whitespace-nowrap"><div className="w-3 h-3 bg-amber-900/40 border border-[#a0714a]/40 rounded" /><span className="text-xs text-[#857460]">개인</span></div></div><div className="h-full p-4" style={{ height: 'calc(100% - 52px)' }}>{scheduleViewMode === 'month' && <MonthView />}{scheduleViewMode === 'week' && <WeekView />}</div></div>
    </div>);
};

export default DashboardTab;
